name:                24colors
version:             0.1.0.0
github:              "fl215/24colors"
license:             MIT
author:              "Execute"
maintainer:          "execute@erisws.com"
copyright:           "Execute"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/24colors#readme>

dependencies:
  - base >= 4.7 && < 5
  - brillo
  - apecs-brillo
  - apecs
  - text
  - linear
  - random
  - tasty
  - tasty-hunit

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - GeneralizedNewtypeDeriving
  - BlockArguments
  - OverloadedStrings
  - MultiWayIf
  - TupleSections

library:
  source-dirs: src

executables:
  24colors-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - 24colors

tests:
  24colors-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - 24colors
